# Site name
name:               "Bergrós Gígja"

# Colors:
accentcolor:        "#e07b39"

# Analytics
google_analytics:   UA-164668668-1

# URL
baseurl:            ""
permalink:          /:year/:month/:day/:title/

# Markdown
markdown:           kramdown

# Navbar
nav:
  - name:           "Projects"
    link:           "projects"
    download:       false
  - name:           "Art"
    link:           "art"
    download:       false
  - name:           "CV"
    link:           "resume.pdf"
    download:       true

# Social links footer
social:
  github:         "bergrosgigja"
  linkedin:       "bergrosgigja"
  instagram:      "bergrosgigja"
  #facebook:       ""
  #twitter:        ""
  #youtube:        ""

sass:
  style:            :compressed
  sass_dir:         _sass

plugins:
  - jemoji

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

art:
  - name:           "Woman in water, acrylic"
    image:           "../assets/art/IMG_swimmer.jpg"
  - name:           "Beans, acrylic"
    image:           "../assets/art/IMG_beans.jpg"
  - name:           "After party, acrylic"
    image:           "../assets/art/IMG_party.jpg"
  - name:           "Chonkers, acrylic"
    image:           "../assets/art/IMG_cat.jpg"
  - name:           "Woman in gold, acrylic"
    image:           "../assets/art/IMG_woman.jpg"
  - name:           "Baby, acrylic"
    image:           "../assets/art/IMG_baby.jpg"
  - name:           "Red Monkey, water color"
    image:           "../assets/art/IMG_monkey.jpg"